version: '3.7'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "8181:80"     
      - "1234:1234"    
    volumes:
      - ./nginx:/etc/nginx/conf.d  
      - ./app/public:/app/public   


  app:
    build: .
    volumes:
      - ./app:/app                 
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - BYEBUG_PORT=1234
      - DATABASE_URL=postgres://postgres:labzz@db:5432/postgres
      - REDIS_URL=redis://redis:6379/1
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"                
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: labzz
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"             

  redis:
    image: redis:alpine
    ports:
      - "6380:6380"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"                
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data:
