default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: labzz
  host: db
  port: 5432
  pool: 5
  
development:
  <<: *default
  database: labzz_development

test:
  <<: *default
  database: labzz_test

production:
  <<: *default
  database: labzz_production